### PR TITLE
switching numpy version by python version

### PR DESCRIPTION
**Pull request by Gldkslfmsd**
#49 
#36

### CODE REVIEW

**Comment by Gldkslfmsd** [comment]
The installation works for me with p3.6.9, and sample-data demo as well. 
However, ideally we should have test module and Travis CI to test if everything works with this numpy version.

**Comment by obo** [comment]
@Matus, could you please resolve this correctly? Thanks! O.

**Comment by mzilinec** [comment]
@Gldkslfmsd are you sure that it doesn't install with Python3.7? It downloads correct version for me even without that.

**Comment by Gldkslfmsd** [comment]
> @Gldkslfmsd are you sure that it doesn't install with Python3.7? It downloads correct version for me even without that.

It does. The problem was with 3.6.

**Comment by mzilinec** [comment]
I merged it but modified so that it will also keep older versions.

**Pull request merged**
